require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - app.rb
    - db/schema.rb
    - vendor/**/*

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb' # Migrations can be long

Metrics/BlockLength:
  Exclude:
    - 'db/migrate/*.rb' # Migrations can be long
    - 'spec/**/*.rb' # Specs just have large blocks

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb' # Expect change blocks are ok
