shared:
  issuer: lti_launcher
  force_ssl: <%= ENV.fetch('FORCE_SSL', 0).to_i == 1 %>
  encryption_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

test:
  domain: <%= ENV.fetch('DOMAIN', 'localhost:8383') %>

development:
  domain: <%= ENV.fetch('DOMAIN', 'localhost:9393') %>

production:
  domain: <%= ENV.fetch('DOMAIN', nil) %>
