shared:
  issuer: lti_launcher
  force_ssl: <%= ENV.fetch('FORCE_SSL', 0).to_i == 1 %>
  encryption_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

test:
  secret_key_base: 1dba623464ca1504fc59a1592e3770d8c37e58e88235fa176f9cea08fced203f5b2d7d02fdb79b2ec8c38ae8ba971707f837b96f3573c5d57abd6dc460ec679b
  domain: <%= ENV.fetch('DOMAIN', 'localhost:8383') %>

development:
  secret_key_base: 808cf961cde280fd5e3a37bbf443c98a04f78852b0c7a0c6e62fa3c3116fa532e8bccaa52061e8e10f0bdafae466e86ffd9edffb33da084afbaa983a789853fe
  domain: <%= ENV.fetch('DOMAIN', 'localhost:9393') %>

production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', nil) %>
  domain: <%= ENV.fetch('DOMAIN', nil) %>
